### PR TITLE
update README and test to avoid react 15.2.0 's unknown properties warning

### PR DESCRIPTION
**Pull request by Darmody**

### CODE REVIEW

**Comment by jasonslyvia** [comment]
it's kind of tedious to manually assign these props :(

before merging, I'd like to check if there is another possibility to do this without resulting React warnings.

**Comment by Darmody** [comment]
@jasonslyvia maybe create a `SortableContainer` component to help developer do this job?

**Comment by jasonslyvia** [comment]
Actually it feels right, care to send some PR (maybe another one, so we can better decide which is the desired behaviour) ?

**Comment by Darmody** [comment]
@jasonslyvia Make sense. I can create another one.

**Comment by jasonslyvia** [comment]
closed in favour of #61

**Pull request closed without merging**
