### PR TITLE
bump react peer dependency

### PR DESCRIPTION
**Pull request by spalger**
Since #83 it seems react-anything-sortable works fine with react 16. Tests also pass when forced to run with react 16.

### CODE REVIEW

**Comment by spalger** [comment]
I know the repo is marked "INACTIVE", but is there any chance of this getting merged?

**Comment by jasonslyvia** [comment]
sure, sorry for kept you waiting for this

**Comment by spalger** [comment]
Thanks @jasonslyvia!

**Comment by spalger** [comment]
Plan to release to npm?

**Comment by jasonslyvia** [comment]
`1.7.4` it is, sorry the delay.

**Comment by spalger** [comment]
Thanks again @jasonslyvia, no worries

**Pull request merged**
