### PR TITLE
Working version for Chrome browser on touch enabled devices

### LINKED ISSUE #23: Not working in touch enabled deviced
This is not working in chrome. No elements are being dragged. I'm using Chrome v46.
I also tested it on firefox. It is working there.

### PR DESCRIPTION
**Pull request by dev-mg**
Fix #23

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Thanks, before merging, I'd like to test it on some mobile platforms to make sure nothing is broken.

**Comment by jasonslyvia** [comment]
Sorry for the delay, I've been tested this on several major platforms and it seems working okay.
So I'll merge this and update the demo, but hold the npm package release until working on Windows 8 Tablet is confirmed.

**Comment by aduggleby** [comment]
Hi Jason, just to confirm: the current release 1.3.6 has this fix or are you still waiting on Windows 8 Tablet confirmation?

**Comment by jasonslyvia** [comment]
hi @aduggleby , it's confirmed working, see [this](https://github.com/jasonslyvia/react-anything-sortable/issues/23#issuecomment-193638887)

**Comment by jasonslyvia** [comment]
1.3.6 has fixed this

**Pull request merged**
