### PR TITLE
Add component prop to SortableContaienr, and make README more clear

### LINKED ISSUE #71: Get `SortableContainer` usage straight
Currently it seems `SortableContainer` is not working as desired

### PR DESCRIPTION
**Pull request by Darmody**
To resolve #71 

Make it clear to separate `SortableContainer` and User's own component.Then it can accept React component.

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Really appreciate your work here! kinda busy these days, I will take a closer look asap.

**Comment by Darmody** [comment]
@jasonslyvia Sorry for make this thing confused.

**Comment by chinesedfan** [comment]
@Darmody Seems good now. Nice job!

ps. Fix lots of typos `SortableContaienr` and how about excluding the auto generated `lib/index.js` file in your pr?

**Comment by Darmody** [comment]
@chinesedfan That's great! Sure, I will fix those typos.

**Comment by Darmody** [comment]
@chinesedfan @jasonslyvia code updated

**Pull request closed without merging**
