### PR TITLE
Allow force dragging direction (vertical/horizontal)

### PR DESCRIPTION
**Pull request by hvergara**
Added logic to force dragging direction (vertical or horizontal) when needed.
It basically force position property (depending on direction, top or left) to initial offset value.

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Looks good, would you might adding corresponding tests for `direction` props?

**Comment by jasonslyvia** [comment]
Brilliant work, thanks!

**Comment by jasonslyvia** [comment]
Are you expecting an immediate release or should I wait until it's necessary?

**Comment by hvergara** [comment]
Don't worry, I can wait 😉

**Comment by jasonslyvia** [comment]
Cool.

**Comment by quentind** [comment]
Hey !

Would love a release for this ;)

**Comment by jasonslyvia** [comment]
@quentind it's been released as `1.5.0`

**Comment by quentind** [comment]
Installing the package with `npm install react-anything-sortable@1.5.0` give me a version that doesn't include this PR. I can't see any `1.5.0` tag or release on Github.

Am I missing something ? Thanks.

**Comment by jasonslyvia** [comment]
Oh it seems like for some reason `1.5.0` doesn't include the latest build files, weird.

**Comment by jasonslyvia** [comment]
`npm publish` just hangs 
image

**Comment by jasonslyvia** [comment]
@quentind after struggling with npm, `1.5.2` finally shipped with the correct built files.

**Comment by quentind** [comment]
@jasonslyvia Great, thanks !

**Pull request merged**
